name: Terraform CI

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.8'

      - name: Check formatting
        working-directory: ./terraform
        run: terraform fmt -check -diff

      - name: Init (no backend)
        working-directory: ./terraform
        run: terraform init -backend=false

      - name: Validate syntax
        working-directory: ./terraform
        run: terraform validate
